use USERS

CREATE TABLE TAIKHOAN (
[USERNAME]     VARCHAR (100) primary key NOT NULL,
[PASSWORD]     VARCHAR (100) NOT NULL,
[EMAIL]        VARCHAR (100) NULL,
[MOBILENUMBER] VARCHAR (50)  NULL,
[FULLNAME]     VARCHAR (50)  NULL,
); 